I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 216, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 531, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 531, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 542, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
AttributeError: 'Hallway_CoinBag' object has no attribute 'verbcalled'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 216, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 531, in script
    python hide:
  File "C:\Users\Me Again\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Me Again\Downloads\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 531, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 542, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
  File "C:\Users\Me Again\Downloads\renpy-8.2.0-sdk\renpy\loadsave.py", line 828, in load
    roots, log = loads(log_data)
  File "C:\Users\Me Again\Downloads\renpy-8.2.0-sdk\renpy\compat\pickle.py", line 100, in loads
    return load(io.BytesIO(s))
  File "C:\Users\Me Again\Downloads\renpy-8.2.0-sdk\renpy\compat\pickle.py", line 97, in load
    return up.load()
AttributeError: 'Hallway_CoinBag' object has no attribute 'verbcalled'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Coding Proficiency Demo 1.0
Thu Mar 14 19:34:18 2024
